### ISSUE TITLE
Max pull value and visible size option

### ISSUE THREAD

**Issue by AnthonyFaxlandez** [zhigang1992/ZGParallelView#3]
I'm loving this so far. There are two things though that I either can't figure out or are missing.

1) When you pull down far enough the head view ends and all you see is the background color of the tableview. Is there a way to stop scrolling once you hit the top of the head view? 

2) Is there a way to set how much of the head view is visible? If the head view is 320 high, I'd like to be able to decide if I want to show 100 or 150 before scrolling. 

Thanks.

**Comment by zhigang1992** [comment]
1) yes, let could be done. Maybe I will add a option to it.
2) there is not such API so far, you can use the radio to control it for now. Set it to be 100/320 or 150/320. But I will add it as soon as I can. 

Thx for the feedback.;)

**Comment by AnthonyFaxlandez** [comment]
Any time, thanks for your response :) 

1)That would be awesome. I'll be looking forward to it if you do add it
2)That made me realize I didn't fully understand the ratio. Now I do and I think that should suffice. Again, thanks :)

**Comment by zhigang1992** [comment]
hey, I have added the cutOffAtMax option. Check out the [Dev branch](https://github.com/zhigang1992/ZGParallelView/tree/Dev). I will merge it to the Master after it test out. :+1:  have a nice day.
