### ISSUE TITLE
New fuctionality

### ISSUE THREAD

**Issue by ghost** [zhigang1992/ZGParallelView#5]
Could you please create the new functionality, so when the user is pulling the screen down the header view is exposed from top and bottom (current behavior). When reaching to the end of the area from the top, the header view will be exposed from the bottom only.

So the header is exposed from top and bottom first, then from the bottom only.

It would be very very appreciated. Thank you.

**Comment by zhigang1992** [comment]
take a look at v0.1.4. I think it has what you need. `Stick to the top`?

**Comment by zhigang1992** [comment]
[This](https://github.com/zhigang1992/ZGParallelView/tree/SubImage) branch has a the Example App for SubView under the ParallelView
