### ISSUE TITLE
It's possible to see the background...

### ISSUE THREAD

**Issue by ghost** [zhigang1992/ZGParallelView#6]
It's possible to see the background above the header if scrolled fast in the ZGScrollViewStyleCutOffAtMax mode.

Screenshot:

![bcg](https://f.cloud.github.com/assets/2511266/195780/d84c5d70-7ffe-11e2-9c5a-8f9b86822f62.png)

**Comment by zhigang1992** [comment]
Thx for pointing it out, but honestly I don't know how to fix it yet... Sorry

**Comment by zhigang1992** [comment]
Luckly it seemed to be okay on device.

**Comment by zhigang1992** [comment]
Hey, take a look at commit [2ecb88](https://github.com/zhigang1992/ZGParallelView/commit/2ecb888811ebfd1c90173f5b9ce6eaf0dbac76b5).
It should fix it.
thx for the feedback :+1:
