### ISSUE TITLE
Overriding -dealloc in a category is fatal.

### ISSUE THREAD

**Issue by bbum** [zhigang1992/ZGParallelView#8]
Overriding -dealloc in a category is fatal;  it replaces the existing implementation, ensuring that every UITableView deallocation will, at best, leak and, at worst, crash or yield undefined behavior.

**Comment by bbum** [comment]
As well, you shouldn't be overriding the KVO methods, either (or any other method of the original class) in a category.

**Comment by ehuynh** [comment]
any chance for a new version podspec

**Comment by zhigang1992** [comment]
@ehuynh Really sorry, it's updated now.

**Comment by ehuynh** [comment]
Thanks heaps

**Comment by arturdev** [comment]
Hi. 
Here is the right way to implement -dealloc method in Category:

```
//...
#import <objc/runtime.h>
#import <objc/message.h>

+ (void)load
{
    Method origMethod = class_getInstanceMethod([self class], NSSelectorFromString(@"dealloc"));
    Method newMethod = class_getInstanceMethod([self class], @selector(my_dealloc));
    method_exchangeImplementations(origMethod, newMethod);
}

- (void)my_dealloc
{
   // do your logic here


    //this calls original dealloc method
    [self my_dealloc];
}
```

This method calls Swizzling :)

**Comment by zhigang1992** [comment]
Nice, thx a lot for that

**Comment by guxianxiong** [comment]
@bbum,  Overriding -dealloc in a A's category(viewcontroller), as we known, it will override A' s dealloc.
But when i release A(whaterver in arc or noarc), the app will run  A's dealloc() )(called by system's [uiviewcontroller release]) then category's dealloc().
so my question is, in this case, since A's dealloc was called by system release. why the app would still crash?  Can you do me a favor and tell me some much more details about this?

**Comment by bbum** [comment]
@guxianxiong If you override a method of a class -- dealloc or otherwise -- in a category, then the original implementation is lost and will never be called.  It is a flat out replacement.

@arturdev While swizzling can sort-of/kind-of get the behavior you want, the implementation you've shown will lead to an infinite loop (if I'm playing computer in my head correctly).

In any case, swizzling a method on a system framework is verboten and grounds for an app to be rejected from the app store(s).

**Comment by guxianxiong** [comment]
@bbum 
Thank you for your quick reply! and I found the reason which cause my problem. Because I have another uiviewcontroller's category in which i use method swizzling for dealloc().

**Comment by lbencs** [comment]
@arturdev 
Thank you for your method.
I get a question。  When i use this method。 All the Class will call this message(my_dealloc).  
so ,i guess this will cause  some other unknown problems？

**Comment by arturdev** [comment]
@lbencs Well, it depends on what class will you add that category
